services:
  webapp:
    build: .
    container_name: webapp
    hostname: webapp
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - prometheus_network

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp
    networks:
      - prometheus_network

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - webapp
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus_network

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - prometheus_network

networks:
  prometheus_network:
    driver: bridge
